### PR TITLE
Behat setup

### PR DESCRIPTION
**Pull request by aritnath1990**

### CODE REVIEW

**Comment by aritnath1990** [comment]
manual comment check

**Comment by aritnath1990** [comment]
Manual comment from GitHub UI

**Comment by aritnath1990** [comment]
Manual comment from GitHub UI-2

**Comment by aritnath1990** [comment]
Sample comment

**Comment by aritnath1990** [comment]
Created via API

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
Created via API By Arit

**Comment by aritnath1990** [comment]
.$at.

**Comment by aritnath1990** [comment]
Nath Arit

**Comment by aritnath1990** [comment]
Test Report pass

**Comment by AHSowner** [comment]
Test Report pass

**Comment by AHSowner** [comment]
Test Report pass

**Comment by AHSowner** [comment]
Test Report pass

**Comment by AHSowner** [comment]
Test Report pass

**Comment by AHSowner** [comment]
Test Report pass

**Comment by aritnath1990** [comment]
[CommentManuallTest.txt](https://github.com/shrimala/ahsweb/files/308972/CommentManuallTest.txt)

**Comment by AHSowner** [comment]
Test Report pass

**Comment by aritnath1990** [comment]
[CommentManuallTest.txt](https://github.com/shrimala/ahsweb/files/309002/CommentManuallTest.txt)

**Comment by AHSowner** [comment]
Test Report pass

**Comment by aritnath1990** [comment]
[CommentManuallTest.txt](https://github.com/shrimala/ahsweb/files/309006/CommentManuallTest.txt)

**Comment by AHSowner** [comment]
arit

**Comment by AHSowner** [comment]
arit arit

**Comment by AHSowner** [comment]
arit arit 009

**Comment by AHSowner** [comment]
arit arit 00dnfksadljfljadlsjlkfjlkasjdlkjlksajljdjaslkdjljaklsjkdklajskldjalsj askdjhas kd as da9

**Comment by AHSowner** [comment]
1 scenario (1 passed)2 steps (2 passed)0m002s (1025Mb)

**Comment by AHSowner** [comment]
1 scenario (1 passed)2 steps (2 passed)0m005s (1026Mb)

**Comment by AHSowner** [comment]
..1 scenario (1 passed)2 steps (2 passed)0m0.05s (10.26Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.05s (10.26Mb)

**Comment by aritnath1990** [comment]
[CommentManuallTest.txt](https://github.com/shrimala/ahsweb/files/310151/CommentManuallTest.txt)
Manually post the comment to check that, file upload and text both working together or not

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.07s (10.26Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Comment by AHSowner** [comment]
..  1 scenario (1 passed) 2 steps (2 passed) 0m0.02s (10.25Mb)

**Pull request closed without merging**
